name: Selenium Framework Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Enable manual triggering

jobs:
  build:
    name: Build Framework
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B clean compile
      
    - name: Run unit tests
      run: mvn -B test -Dgroups="unit"
      
    - name: Package framework
      run: mvn -B package -DskipTests
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: selenium-framework
        path: target/*.jar
        
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: java
        
    - name: Run Maven Checkstyle
      run: mvn checkstyle:check
      continue-on-error: true
      
    - name: Run Maven SpotBugs
      run: mvn spotbugs:check
      continue-on-error: true
      
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      
    - name: Generate code quality report
      run: |
        mkdir -p code-quality-reports
        touch code-quality-reports/summary.txt
        echo "Code Quality Analysis Summary" > code-quality-reports/summary.txt
        echo "Date: $(date)" >> code-quality-reports/summary.txt
        echo "Checkstyle and SpotBugs analysis completed" >> code-quality-reports/summary.txt
        
    - name: Upload code quality report
      uses: actions/upload-artifact@v3
      with:
        name: code-quality-reports
        path: code-quality-reports/